name: Deploy to Hostinger
on:
  push:
    branches:
      - master
jobs:
  web-deploy:
    name: Sync Changes
    runs-on: ubuntu-latest
    steps:
    - name: Get Latest Code
      uses: actions/checkout@v3
    
    - name: Sync Files via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: /public_html/wp-content/themes/rwaqtheme/
        dangerous-clean-slate: false
